version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: developerTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4578:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data

  app:
    container_name: project-api-spring
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/developerTest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: GMT-3
    volumes:
      - "./:/app"
      - ~/.m2:/root/.m2
    working_dir: "/app"
    command: mvn clean spring-boot:run
    depends_on:
      - postgres
